name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Change to frontend directory
      run: ls ; pwd ;  cd frontend 


    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4  # You can use a different action if preferred
      with:
        branch: gh-pages  # Branch to deploy the built assets to
        folder: dist  # Folder where the built assets are located within the 'frontend' directory
